name: AZLifestyle
favicon: null
layout_spectrum: 0.87522
typography_spectrum: 0.9397934882435948
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#525252'
    - '#7b7b7b'
    - '#ffffff'
    - '#afafaf'
  brandStrength: 0.4773142070043832
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.7175938603468239
purpose: []
