name: AZLifestyle
favicon: null
layout_spectrum: 0.87522
typography_spectrum: 0.9397934882435948
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4773142070043832
  lightness: 0.1611052171792835
  saturation: 0.8056975589133799
  rhythmicContrast: 0.7175938603468239
purpose: []
