name: AZLifestyle
favicon: null
layout_spectrum: 0.24738
typography_spectrum: 0.17713
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#525252'
    - '#7b7b7b'
    - '#ffffff'
    - '#afafaf'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
